# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ImageBrowser' do
  use_frameworks!
	pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'Masonry'

  target 'ImageBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
