# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SmartWebViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartWebViewDemo
#  pod 'SnapKit', '~> 5.7.0'
  pod 'LookinServer', :configurations => ['Debug']

  target 'SmartWebViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartWebViewDemoUITests' do
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['CODE_SIGN_IDENTITY'] = ''
    config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
  end
end
